# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ArtWall' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'SDWebImage', '~> 4.0'
  pod 'AFNetworking', '~> 3.0'
  pod 'DateTools'
  pod 'Fabric'
  pod 'Crashlytics'
  pod 'RFOverlayScrollView'

  target 'ArtWallTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ArtWallUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
